### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by MrMaksimize** [COSD-PANDA/seaboard#20]
- [ ] Admin settings edit files in the right place
- [ ]  Config gets edited in the right place
- [ ] Google analytics is on
- [ ] GTM is on
- [ ] Full Story is on
- [ ] Keen is on for dataset downloads (MAYBE)
